= CS3223 Project
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Project Team Members:

* Chua Wei Wen (A0156034M)
* Khor Shao Liang (A0160529E)
* Sim Kwan Tiong, Damien (A0155983N)

== Introduction
This document provides information on the features that has been implemented into the query processing engine.

== Implementation
The following features are implemented:

=== Block-Nested Loop Join

=== External Sort
The external sort algorithm is written in `ExternalSort` as an `Operator` object. The `table` holds the data, the `joinAttribute` is the `Attribute` that is used to sort the data in `table`. `numBuff` is the number of buffers and `flag` indicates whether to eliminate duplicates for distinct operation (see Section 2.4).

----
public ExternalSort(Operator table, Attribute joinAttribute, int numBuff, boolean flag) {
        super(OpType.SORT);
        this.table = table;
        this.numBuff = numBuff;
        this.batchSize = Batch.getPageSize()/table.getSchema().getTupleSize();
        this.joinAttribute = joinAttribute;
        this.fileNum = instanceNum++;
        this.isDistinct = flag;
    }
----

Since external sort is required to generate temporary files to store intermediate results, a unique variable is assigned to each instance of `ExternalSort` created. This is achieved by creating a static variable `instanceNum`, which is assigned to `fileNum` in the constructor as the unique number. The `instanceNum` is incremented which will be used as the next unique number when another `ExternalSort` object is created.

The name of the temporary files will contain the integers `fileNum`, `passNum` and `runNum` to differentiate the files.

The external sort is done in the `open` method. There are two phases in external sort:

. Generate sorted runs - implemented in the method `generateRuns`.
. Merge the sorted runs - implemented in the method `executeMerge`.

A `Vector` object `sortedRunFiles` holds the file pointer to the files that are generated during the first phase.

==== Generate Sorted Runs
In the `generateRuns` method, a `Vector` object `batchList` that holds `Batch` object simulates the buffers that are available to hold the pages. Pages are added into the `batchList` until it is "full", in which the `batchList` will be passed to another method `generateSortedRun`.

In `generateSortedRun`, all the tuples are loaded from the pages and stored in a temporary `Vector` object `tupleList`. The `tupleList` is sorted using `SortComparator` which sorts the list based on the join attribute. After the list is sorted, the tuples will be added to the pages. If the page is full, the page `currentBatch` will be added to `sortedRun`. Pages will be added to `sortedRun` until it is full, in which it returns the completed sorted run.

The `sortedRun` will be passed to `writeRun` method, which writes to a temporary file to simulate writing of data to disk with a unique file name. The `File` object that holds the file pointer to the generated temporary files will be returned, and it will be stored in the `Vector` object `sortedRunFiles`. This allows easier access to the files during the second phase.

The `generateRuns` will run until all the tuples have been read, and all the sorted runs are generated.

==== Merge Sorted Runs
The second phase is executed in the `executeMerge` method. The number of buffers available `numUsableBuff` simulates the merging phase, in which one buffer is used for output, while the rest of the buffers are used for merging.

The while loop keeps executing until all the runs have been merged into a single sorted run. A `Vector` object `newSortedRuns` keeps track of the new files containing the new sorted runs that are merged. The `startIndex` and `endIndex` essentially picks the indexes of the file pointers stored in `sortedRunFiles` that can be placed into the available buffer space `numUsableBuff`. These files are picked and stored in a `List` object `runsToSort`. This list is passed to another method `mergeSortedRuns`.

In the `mergeSortedRuns`, `inputBuffers` holds the content of the pages that will be loaded from the file. The `inputStreams` is a list of `ObjectInputStream` object that reads in the respective `File` object from the `sortedRuns`. The `for` loop below reads in each page that are stored in the `File` and place it into the `inputBuffers`.

----
for (ObjectInputStream ois : inputStreams) {
    Batch batch = readBatch(ois);
        inputBuffers.add(batch);
}
----

The `int[]` array `batchTrackers` keeps track of the number of tuples that has been added to the `outputBuffer` for each `inputBuffers`. The `Tuple` object `smallest` keeps track of the smallest tuple encountered so far in the next `for` loop, and the `indexOfSmallest` keeps track of the page index of the tuple.

After the smallest tuple has been found, the `backTrackers` for the index of the `inputBuffers` where the smallest tuple is found will be incremented. This indicates that one additional tuple will be added to the `outputBuffer` and will then point to the next tuple in that buffer. If all the tuples in that `inputBuffer` has been added to the `outputBuffer`, that input buffer will be replaced with a new page, and the `batchTrackers` will be reset to 0 to point to the first tuple.

Next it will check whether `isDistinct` is true. This will be described in Section 2.4. Otherwise, the tuple will be added to the `outputBuffer`.

When the `outputBuffer` is full, it will be written to a temporary file. The whole process is repeated until a sorted run is generated and a `File` object holding the pointer to the file will be returned. This file will be added to `newSortedRuns` that contains the newly merged sorted runs. This process is repeated until the sorted runs are merged. The old `sortedRunFiles` will be deleted by the `clearTempFiles` method, and the `sortedRunFiles` will point to the `newSortedRuns`.

The whole process repeats until there is only one sorted run left.

==== Passing of data
In `next`, `ExternalSort` will pass the sorted table data in pages to the `Operator` object that calls `ExternalSort`.

==== Closing
In `close`, `ExternalSort` will close the `table` and clear the single sorted run file data.

=== Sort-Merge Join

=== Distinct

=== Greedy Optimizer
